routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[
    'uses' => 'HomeController@index',
    'as' => 'home'
]);

Route::group([
    'prefix' => '/admin',
    'middleware' => ['auth','role:owner|admin'],
    'as' => 'admin.'
], function () {

    Route::get('/',[
        'uses' => 'admin\AdminController@index',
        'as' => 'index'
    ]);

    Route::get('/users',[
        'uses' => 'admin\UsersController@index',
        'as' => 'users'
    ]);

    Route::get('/user/{id}',[
        'uses' => 'admin\UsersController@editUser',
        'as' => 'users.edit'
    ]);

    Route::put('/user/{id}/update',[
        'uses' => 'admin\UsersController@updateUser',
        'as' => 'users.update'
    ]);

    Route::post('/user/{id}/roles',[
        'uses' => 'admin\UsersController@updateUserRoles',
        'as' => 'users.roles'
    ]);

    Route::post('/user/{id}/delete',[
        'uses' => 'admin\UsersController@deleteUser',
        'as' => 'users.delete'
    ]);

    Route::get('/roles',[
        'uses' => 'admin\UsersController@permissions',
        'as' => 'permissions',
        'middleware' => 'permission:edit-permissions'
    ]);

    Route::post('/roles/update',[
        'uses' => 'admin\UsersController@updateRole',
        'as' => 'role.update',
        'middleware' => 'permission:edit-permissions'
    ]);

    Route::get('/roles/get',[
        'uses' => 'admin\UsersController@getPermissions',
        'as' => 'role.get',
        'middleware' => 'permission:edit-permissions'
    ]);

    Route::get('/orders',[
        'uses' => 'admin\OrdersController@index',
        'as' => 'orders.get',
    ]);

    //Please do not remove this if you want adminlte:route and adminlte:link commands to works correctly.
    #adminlte_routes
    Route::resource('comments', 'admin\CommentsController');

    Route::resource('authors', 'admin\AuthorsController');

    Route::resource('genres', 'admin\GenresController');

    Route::resource('books', 'admin\BooksController');

});

Route::group([
    'middleware' => 'auth'
], function (){

    Route::post('/book/{id}/comment', [
        'uses' => 'CommentsController@store',
        'as' => 'user.comment.create',
    ]);

    Route::post('/cart', 'CartController@addToCart');

    Route::post('/cart/quantity', 'CartController@getTotalQuantity');

    Route::post('/cart/quantity/add', 'CartController@addItem');

    Route::post('/cart/quantity/deduct', 'CartController@deductItem');

    Route::post('/cart/delete', 'CartController@deleteItem');

    Route::get('/cart/clear', 'CartController@clearCart')->name('user.clear.cart');

    Route::get('/book/{id}', 'BooksController@show')->name('book.show');

    Route::get('/author/{id}', 'AuthorsController@show')->name('author.show');

    Route::get('/genre/{id}', 'GenresController@show')->name('genre.show');


    Route::get('/cart/show', [
        'uses' => 'CartController@show',
        'as' => 'user.cart.show',
    ]);

    Route::post('/cart/show', [
        'uses' => 'CartController@updateStripeDetails',
        'as' => 'user.stripe.update',
    ]);

    Route::post('/cart/buy', [
        'uses' => 'CartController@buy',
        'as' => 'user.buy',
    ]);
});

Route::get('/test', [
    'uses' => 'HomeController@test',
    'as' => 'test'
]);

Route::get('/auth/facebook', [
    'uses' => 'AuthController@fakeLogin',
]);
Route::get('/auth/google', [
    'uses' => 'AuthController@fakeLogin',
]);

Auth::routes();

Route::any('/stripe/webhook', 'WebhookController@handle');

app/models/Genre.php
<?php

namespace App\models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Genre extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [
        'genre'
    ];

    public $timestamps = false;

    public function books()
    {
        return $this->belongsToMany(Book::class, 'genres_books_pivot');
    }

}

app/Http/Controllers/GenresController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Repositories\GenreRepository;
use App\Validators\GenreValidator;


class GenresController extends Controller
{

    /**
     * @var GenreRepository
     */
    protected $repository;

    /**
     * @var GenreValidator
     */
    protected $validator;

    public function __construct(GenreRepository $repository, GenreValidator $validator)
    {
        $this->repository = $repository;
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $genre = $this->repository->with('books')->find($id);

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $genre,
            ]);
        }

        return view('genres.show', compact('genre'));
    }

}

app/Http/Controllers/admin/GenresController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Http\Requests;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;
use App\Http\Requests\GenreCreateRequest;
use App\Http\Requests\GenreUpdateRequest;
use App\Repositories\GenreRepository;
use App\Validators\GenreValidator;


class GenresController extends Controller
{

    /**
     * @var GenreRepository
     */
    protected $repository;

    /**
     * @var GenreValidator
     */
    protected $validator;

    public function __construct(GenreRepository $repository, GenreValidator $validator)
    {
        $this->repository = $repository;
        $this->validator  = $validator;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->repository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));
        $genres = $this->repository->with('books')->all();

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $genres,
            ]);
        }

        return view('admin.genres.index', ['genres' => $genres, 'user' => \Auth::user()]);
    }

    public function create()
    {
        return view('admin.genres.edit', ['user' => \Auth::user()]);
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  GenreCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(GenreCreateRequest $request)
    {

        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_CREATE);

            $genre = $this->repository->create($request->all());

            $response = [
                'message' => 'Genre created.',
                'data'    => $genre->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->route('admin.genres.index')->with('message', $response['message']);
        } catch (ValidatorException $e) {
            if ($request->wantsJson()) {
                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }


    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $genre = $this->repository->with('books')->find($id);

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $genre,
            ]);
        }

        return view('admin.genres.show', ['genre' => $genre, 'user' => \Auth::user()]);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $genre = $this->repository->find($id);

        return view('admin.genres.edit', ['genre' => $genre, 'user' => \Auth::user()]);
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  GenreUpdateRequest $request
     * @param  string            $id
     *
     * @return Response
     */
    public function update(GenreUpdateRequest $request, $id)
    {

        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_UPDATE);

            $genre = $this->repository->update($request->all(), $id);

            $response = [
                'message' => 'Genre updated.',
                'data'    => $genre->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->route('admin.genres.index')->with('message', $response['message']);
        } catch (ValidatorException $e) {

            if ($request->wantsJson()) {

                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deleted = $this->repository->delete($id);

        if (request()->wantsJson()) {

            return response()->json([
                'message' => 'Genre deleted.',
                'deleted' => $deleted,
            ]);
        }

        return redirect()->route('admin.genres.index')->with('message', 'Genre deleted.');
    }
}

resources/views/admin/genres/edit.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
    Genres
@endsection

@section('contentheader_title')
    @if(isset($author))
        Genre {!! $genre->genre !!}
    @else
        New genre
    @endif

@endsection

@section('menu_links')
    <li><a href="{!! route('admin.genres.index') !!}"><i class="fa fa-list-alt"></i> Genres </a></li>
    <li class="active"><i class="fa fa fa-list"></i> Edit Genre</li>
@endsection


@section('main-content')
    <div class="container-fluid spark-screen">
        <div class="row">
            <div class="col-md-9 col-md-offset-1">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3>Create a new Author</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="panel panel-default creation">

                            @if(isset($genre))
                                {!! Form::model($genre,['files' => true,
                                 'route' => ['admin.genres.update', 'genre' => $genre->id],
                                 'method' => 'put']) !!}
                            @else
                                {!! Form::open(['route' => 'admin.genres.store',
                                'files' => true]) !!}
                            @endif
                            <div class="panel-body">

                                <div class="input-group {{ $errors->has('genre') ? ' has-error' : '' }}">
                                    <span class="input-group-addon" id="genre">Name</span>
                                    <input type="text" name="genre" class="form-control" placeholder="Genre name" aria-describedby="genre" value="{!! isset($genre) ? $genre->genre : null !!}">
                                </div>
                                @if ($errors->has('genre'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('genre') }}</strong>
                                    </span>
                                @endif
                                <br>

                            </div>
                            <div class="panel-footer">
                                {!! Form::submit('Submit', ['class' => 'btn btn-success']) !!}
                            </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('adminlte::layouts.partials.scripts')
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
@endsection

resources/views/admin/genres/index.blade.php
@extends('adminlte::layouts.app')

@section('contentheader_title')
    Genres
@endsection

@section('menu_links')
    <li class="active"><i class="fa fa-list-alt"></i> Genres</li>
@endsection

@section('main-content')
    <div class="container-fluid spark-screen">
        <div class="row">
            <div class="col-md-9 col-md-offset-1">
                <div class="box box-primary">
                    @if(\Session::has('message'))
                        <div class="alert alert-success" role="alert">
                            {!! Session::get('message') !!}
                        </div>
                    @endif
                    <div class="box-header">
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <a href="{!! route('admin.genres.create') !!}" class="btn btn-success">Add new genre</a>
                        <div class="table-responsive">
                            <table class="table table-users table-hover">
                                <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Name</th>
                                    <th colspan="3">Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @if( isset($genres))
                                    @foreach($genres as $genre)
                                        <tr>
                                            <td>{!! $genre->id !!}</td>
                                            <td>{!! $genre->genre !!}</td>
                                            <td>
                                                <a class="btn btn-block btn-warning" href="{!! route('admin.genres.edit',['genre' => $genre->id]) !!}">
                                                    Edit
                                                </a>
                                            </td>
                                            <td>
                                                {!! Form::open(['route' => ['admin.genres.destroy', 'genre' => $genre->id], 'method' => 'delete']) !!}
                                                <button type="submit" class="btn btn-block btn-danger">
                                                    Delete
                                                </button>
                                                {!! Form::close() !!}
                                            </td>
                                            <td>
                                                <a class="btn btn-block btn-info" href="{!! route('admin.genres.show',['genre' => $genre->id]) !!}">
                                                    Show books
                                                </a>
                                            </td>
                                        </tr>
                                    @endforeach
                                @endif
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@if(false)
    <div class="box box-success box-solid">
        <div class="box-header with-border">
            <h3 class="box-title">Example box</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div>
            <!-- /.box-tools -->
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            Put your content here
        </div>
        <!-- /.box-body -->
    </div>
@endif

resources/views/admin/genres/show.blade.php
@extends('adminlte::page')

@section('contentheader_title')
    Genres
@endsection

@section('menu_links')
    <li><a href="{!! route('admin.genres.index') !!}"><i class="fa fa-list-alt"></i> Genres </a></li>
    <li class="active"><i class="fa fa fa-list"></i> Show Genre</li>
@endsection

@section('main-content')
	<div class="container-fluid spark-screen">
		<div class="row">
			<div class="col-md-9 col-md-offset-1">
                <div class="panel panel-default">

                    <div class="panel-heading">
                        <h3 class="panel-title">{!! $genre->genre !!}</h3>
                    </div>

                    <div class="panel-body">
                        <div class="list-group">
                            @foreach($genre->books as $book)
                                <a href="{!! route('admin.books.show',['book' => $book->id]) !!}" class="list-group-item">{!! $book->title !!}</a>
                            @endforeach
                        </div>
                    </div>


                </div>
			</div>
		</div>
	</div>
@endsection