routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[
    'uses' => 'HomeController@index',
    'as' => 'home'
]);

Route::group([
    'prefix' => '/admin',
    'middleware' => ['auth','role:owner|admin'],
    'as' => 'admin.'
], function () {

    Route::get('/',[
        'uses' => 'admin\AdminController@index',
        'as' => 'index'
    ]);

    Route::get('/users',[
        'uses' => 'admin\UsersController@index',
        'as' => 'users'
    ]);

    Route::get('/user/{id}',[
        'uses' => 'admin\UsersController@editUser',
        'as' => 'users.edit'
    ]);

    Route::put('/user/{id}/update',[
        'uses' => 'admin\UsersController@updateUser',
        'as' => 'users.update'
    ]);

    Route::post('/user/{id}/roles',[
        'uses' => 'admin\UsersController@updateUserRoles',
        'as' => 'users.roles'
    ]);

    Route::post('/user/{id}/delete',[
        'uses' => 'admin\UsersController@deleteUser',
        'as' => 'users.delete'
    ]);

    Route::get('/roles',[
        'uses' => 'admin\UsersController@permissions',
        'as' => 'permissions',
        'middleware' => 'permission:edit-permissions'
    ]);

    Route::post('/roles/update',[
        'uses' => 'admin\UsersController@updateRole',
        'as' => 'role.update',
        'middleware' => 'permission:edit-permissions'
    ]);

    Route::get('/roles/get',[
        'uses' => 'admin\UsersController@getPermissions',
        'as' => 'role.get',
        'middleware' => 'permission:edit-permissions'
    ]);

    Route::get('/orders',[
        'uses' => 'admin\OrdersController@index',
        'as' => 'orders.get',
    ]);

    //Please do not remove this if you want adminlte:route and adminlte:link commands to works correctly.
    #adminlte_routes
    Route::resource('comments', 'admin\CommentsController');

    Route::resource('authors', 'admin\AuthorsController');

    Route::resource('genres', 'admin\GenresController');

    Route::resource('books', 'admin\BooksController');

});

Route::group([
    'middleware' => 'auth'
], function (){

    Route::post('/book/{id}/comment', [
        'uses' => 'CommentsController@store',
        'as' => 'user.comment.create',
    ]);

    Route::post('/cart', 'CartController@addToCart');

    Route::post('/cart/quantity', 'CartController@getTotalQuantity');

    Route::post('/cart/quantity/add', 'CartController@addItem');

    Route::post('/cart/quantity/deduct', 'CartController@deductItem');

    Route::post('/cart/delete', 'CartController@deleteItem');

    Route::get('/cart/clear', 'CartController@clearCart')->name('user.clear.cart');

    Route::get('/book/{id}', 'BooksController@show')->name('book.show');

    Route::get('/author/{id}', 'AuthorsController@show')->name('author.show');

    Route::get('/genre/{id}', 'GenresController@show')->name('genre.show');


    Route::get('/cart/show', [
        'uses' => 'CartController@show',
        'as' => 'user.cart.show',
    ]);

    Route::post('/cart/show', [
        'uses' => 'CartController@updateStripeDetails',
        'as' => 'user.stripe.update',
    ]);

    Route::post('/cart/buy', [
        'uses' => 'CartController@buy',
        'as' => 'user.buy',
    ]);
});

Route::get('/test', [
    'uses' => 'HomeController@test',
    'as' => 'test'
]);

Route::get('/auth/facebook', [
    'uses' => 'AuthController@fakeLogin',
]);
Route::get('/auth/google', [
    'uses' => 'AuthController@fakeLogin',
]);

Auth::routes();

Route::any('/stripe/webhook', 'WebhookController@handle');

app/models/Book.php
<?php

namespace App\models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Book extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [
        'title',
        'description',
        'image',
        'date',
        'price',
        'file'
    ];

    public $timestamps = false;

    public function authors()
    {
        return $this->belongsToMany(Author::class, 'authors_books_pivot', 'book_id','author_id');
    }

    public function genres()
    {
        return $this->belongsToMany(Genre::class, 'genres_books_pivot');
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function rank()
    {
        $comments = $this->comments;
        $totalRank = 0;
        $rankedComments = 0;
        foreach ($comments as $comment){
            if ($comment->rank){
                $rankedComments ++;
                $totalRank += $comment->rank;
            }
        }
        if ($rankedComments){
            return round($totalRank / $rankedComments, 1);
        }
        return 0;
    }

}

app/Http/Controllers/BooksController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Repositories\BookRepository;
use App\Validators\BookValidator;


class BooksController extends Controller
{

    /**
     * @var BookRepository
     */
    protected $repository;

    /**
     * @var BookValidator
     */
    protected $validator;

    public function __construct(BookRepository $repository, BookValidator $validator)
    {
        $this->repository = $repository;
        $this->validator  = $validator;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->repository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));
        $books = $this->repository->all();

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $books,
            ]);
        }

        return view('books.index', [compact('books'), 'user' => \Auth::user()]);
    }


    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $book = $this->repository->find($id);

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $book,
            ]);
        }

        return view('books.show', compact('book'));
    }


}

app/Http/Controllers/admin/BooksController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Repositories\AuthorRepository;
use App\Repositories\GenreRepository;
use Illuminate\Http\Request;

use App\Http\Requests;
use Prettus\Validator\Exceptions\ValidatorException;
use App\Http\Requests\BookCreateRequest;
use App\Http\Requests\BookUpdateRequest;
use App\Repositories\BookRepository;


class BooksController extends Controller
{

    /**
     * @var BookRepository
     */
    protected $repository;

    /**
     * @var AuthorRepository
     */
    protected $authorRepository;

    /**
     * @var GenreRepository
     */
    protected $genreRepository;


    public function __construct(BookRepository $repository, AuthorRepository $authorRepository, GenreRepository $genreRepository)
    {
        $this->repository = $repository;
        $this->authorRepository = $authorRepository;
        $this->genreRepository = $genreRepository;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->repository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));
        $books = $this->repository->with('authors')->all();

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $books,
            ]);
        }

        return view('admin.books.index', ['books'  => $books, 'user' => \Auth::user()]);
    }

    public function create()
    {
        $authors =  $this->authorRepository->all();
        $genres = $this->genreRepository->all();

        return view('admin.books.edit',  [
            'user' => \Auth::user(),
            'genres' => $genres,
            'authors' => $authors

        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  BookCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(BookCreateRequest $request)
    {

        try {

            $cover = $request->file('image');
            $coverName = $cover->getFilename() . '.' . $cover->getClientOriginalExtension();

            \Storage::disk('covers')->putFileAs(
                '',
                $cover,
                $coverName
            );

            $bookFile = $request->file('file');
            $bookName = $bookFile->getClientOriginalName() . '.' . $bookFile->getClientOriginalExtension();
            \Storage::disk('books')->putFileAs(
                '',
                $bookFile,
                $bookName
            );

            $data = $request->except(['image', 'file', '_token','authors','genres']);
            $data['image'] = $coverName;
            $data['file'] = $bookName;

            $book = $this->repository->create($data);

            foreach ($request->get('genres') as $genreId){
                $genre = $this->genreRepository->find($genreId);
                $book->genres()->attach($genre);
            }

            foreach ($request->get('authors') as $authorId){
                $author = $this->authorRepository->find($authorId);
                $book->authors()->attach($author);
            }

            $response = [
                'message' => 'Book created.',
                'data'    => $book->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->route('admin.books.index')->with('message', $response['message']);
        } catch (ValidatorException $e) {
            if ($request->wantsJson()) {
                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }


    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $book = $this->repository->with('comments')->find($id);

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $book,
            ]);
        }

        return view('admin.books.show', ['book'=> $book, 'user' => \Auth::user()]);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $book = $this->repository->with(['authors','genres'])->find($id);
        $authors =  $this->authorRepository->all();
        $genres = $this->genreRepository->all();

        return view('admin.books.edit', [
            'genres' => $genres,
            'authors' => $authors,
            'book' => $book,
            'user' => \Auth::user()
        ]);
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  BookUpdateRequest $request
     * @param  string            $id
     *
     * @return Response
     */
    public function update(BookUpdateRequest $request, $id)
    {

        try {
            $data = $request->except(['_token', '_method', 'image','file']);

            $book = $this->repository->find($id);

            if ($request->hasFile('image')) {
                \Storage::disk('covers')->delete($book->image);

                $cover = $request->file('image');
                $coverName = $cover->getFilename() . '.' . $cover->getClientOriginalExtension();

                \Storage::disk('covers')->putFileAs(
                    '',
                    $cover,
                    $coverName
                );

                $data['image'] = $coverName;

            }
            if ($request->hasFile('file')){
                \Storage::disk('books')->delete($book->file);

                $bookFile = $request->file('file');
                $bookName = $bookFile->getClientOriginalName();
                \Storage::disk('books')->putFileAs(
                        '',
                        $bookFile,
                        $bookName
                    );

                $data['file'] = $bookName;
            }

            $book = $this->repository->update($data, $id);

            $response = [
                'message' => 'Book updated.',
                'data'    => $book->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->route('admin.books.index')->with('message', $response['message']);
        } catch (ValidatorException $e) {

            if ($request->wantsJson()) {

                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $book = $this->repository->find($id);

        \Storage::disk('covers')->delete($book->image);
        \Storage::disk('books')->delete($book->file);

        $deleted = $this->repository->delete($id);

        if (request()->wantsJson()) {

            return response()->json([
                'message' => 'Book deleted.',
                'deleted' => $deleted,
            ]);
        }

        return redirect()->back()->with('message', 'Book deleted.');
    }
}

resources/views/admin/books/edit.blade.php
@extends('adminlte::layouts.app')

@section('styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">
@endsection

@section('htmlheader_title')
    {!! isset($book) ? 'Book'.$book->title : 'New book' !!}

@endsection

@section('contentheader_title')
    Books
@endsection

@section('menu_links')
    <li><a href="{!! route('admin.books.index') !!}"><i class="fa fa-book"></i> Books </a></li>
    <li class="active"><i class="fa fa-book"></i> Edit Book</li>
@endsection

@section('main-content')
    <div class="container-fluid spark-screen">
        <div class="row">
            <div class="col-md-9 col-md-offset-1">
                <div class="box box-primary">
                    @if(\Session::has('message'))
                        <div class="alert alert-danger" role="alert">
                            {!! Session::get('message') !!}
                        </div>
                    @endif
                    <div class="box-header">
                        <h3>Create a new book</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="panel panel-default creation">

                            @if(isset($book))
                                {!! Form::model($book,[
                                'files' => true,
                                'method' => 'put',
                                'route' => ['admin.books.update', 'book' => $book->id],
                                ]) !!}
                            @else
                                {!! Form::open([
                                'route' => 'admin.books.store',
                                'method' => 'post',
                                'files' => true]) !!}
                            @endif
                            <div class="panel-body">

                                <div class="input-group {{ $errors->has('title') ? ' has-error' : '' }}">
                                    <span class="input-group-addon" id="title">Title</span>
                                    <input type="text" name="title" class="form-control" placeholder="Title" aria-describedby="title" value="{!! isset($book) ? $book->title : old('title') !!}">
                                </div>
                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                                <br>

                                <div class="form-group {{ $errors->has('description') ? ' has-error' : '' }}">
                                    <label for="description">Description</label>
                                    <textarea class="form-control" rows="5" id="description" name="description">{!! isset($book) ? $book->description : old('description') !!}</textarea>
                                </div>
                                @if ($errors->has('description'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                                <div class="input-group {{ $errors->has('authors') ? ' has-error' : '' }}">
                                    <span class="input-group-addon" id="authors">Authors</span>
                                    <select name="authors[]" class="selectpicker form-control" aria-describedby="authors" multiple title="Choose author(s)">
                                        @foreach($authors as $author)
                                        <option value="{!! $author->id !!}" @if(isset($book) && $book->authors->find($author->id)) selected @endif>{!! $author->name !!}</option>
                                        @endforeach
                                    </select>
                                </div>
                                @if ($errors->has('authors'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('authors') }}</strong>
                                    </span>
                                @endif
                                <br>

                                <div class="input-group {{ $errors->has('genres') ? ' has-error' : '' }}">
                                    <span class="input-group-addon" id="authors">Genres</span>
                                    <select name="genres[]" class="selectpicker form-control" aria-describedby="genres" multiple title="Choose genre(s)">
                                        @foreach($genres as $genre)
                                        <option value="{!! $genre->id !!}" @if(isset($book) && $book->genres->find($genre->id)) selected @endif >{!! $genre->genre !!}</option>
                                        @endforeach
                                    </select>
                                </div>
                                @if ($errors->has('genres'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('genres') }}</strong>
                                    </span>
                                @endif
                                <br>



                                <div class="fileinput fileinput-new {{ $errors->has('image') ? ' has-error' : '' }}" data-provides="fileinput">
                                    <span class="btn btn-default btn-file"><span>Choose cover image</span><input type="file" name="image" accept="image" /></span>
                                    <span class="fileinput-filename"></span><span class="fileinput-new">No file chosen</span>
                                </div>
                                @if ($errors->has('image'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('image') }}</strong>
                                    </span>
                                @endif
                                <br>

                                <div class="input-group {{ $errors->has('date') ? ' has-error' : '' }}">
                                    <span class="input-group-addon" id="date">Date (Year)</span>
                                    <input type="text" name="date" class="form-control" placeholder="Date" aria-describedby="date" value="{!! isset($book) ? $book->date : old('date') !!}">
                                </div>
                                @if ($errors->has('date'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('date') }}</strong>
                                    </span>
                                @endif
                                <br>

                                <div class="input-group {{ $errors->has('price') ? ' has-error' : '' }}">
                                    <span class="input-group-addon" id="price">Price</span>
                                    <input type="text" class="form-control" name="price" placeholder="Price" aria-describedby="price" value="{!! isset($book) ? $book->price : old('price') !!}">
                                </div>
                                @if ($errors->has('price'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('price') }}</strong>
                                    </span>
                                @endif
                                <br>

                                <div class="fileinput fileinput-new {{ $errors->has('file') ? ' has-error' : '' }}">
                                    <span class="btn btn-default btn-file"><span>Choose file</span><input type="file" name="file" /></span>
                                    <span class="fileinput-filename"></span><span class="fileinput-new">No file chosen</span>
                                </div>
                                @if ($errors->has('file'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('file') }}</strong>
                                    </span>
                                @endif
                                <br>

                            </div>
                            <div class="panel-footer">
                                {!! Form::submit('Submit', ['class' => 'btn btn-success']) !!}
                            </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>
@endsection

resources/views/admin/books/index.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
    Books
@endsection

@section('contentheader_title')
    Books
@endsection

@section('menu_links')
    <li class="active"><i class="fa fa-book"></i> Books</li>
@endsection

@section('main-content')
    <div class="container-fluid spark-screen">
        <div class="row">
            <div class="col-md-9 col-md-offset-1">
                <div class="box box-primary">
                    @if(\Session::has('message'))
                        <div class="alert alert-success" role="alert">
                            {!! Session::get('message') !!}
                        </div>
                    @endif
                    <div class="box-header">
                        <h3>All Books</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <a href="{!! route('admin.books.create') !!}" class="btn btn-success">Add new book</a>
                        <div class="table-responsive">
                            <table class="table table-users table-hover">
                                <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Title</th>
                                    <th>Author</th>
                                    <th>Cover</th>
                                    <th>Genres</th>
                                    <th>Price</th>
                                    <th colspan="2">Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @if( isset($books))
                                @foreach($books as $book)
                                    <tr>
                                        <td>{!! $book->id !!}</td>
                                        <td>{!! $book->title !!}</td>
                                        <td>
                                            @foreach($book->authors as $bookAuthor)
                                                <a href="{!! route('admin.authors.show', ['author' => $bookAuthor->id]) !!}">
                                                     {!! $bookAuthor->name !!}
                                                </a>
                                            @endforeach
                                        </td>
                                        <td>
                                            <img class="table-image" src="/img/covers/{!! $book->image !!}" alt="">
                                        </td>
                                        <td>
                                            @foreach($book->genres as $bookGenre)
                                                <a href="{!! route('admin.genres.show', ['genre' => $bookGenre->id]) !!}">
                                                    {!! $bookGenre->genre !!}
                                                </a>
                                            @endforeach
                                        </td>
                                        <td>{!! $book->price !!} $</td>
                                        <td>
                                            <a href="{!! route('admin.books.edit',['book' => $book->id]) !!}" class="btn btn-block btn-warning">
                                                Edit
                                            </a>
                                        </td>
                                        <td>
                                            {!! Form::open(['route' => ['admin.books.destroy', 'genre' => $book->id], 'method' => 'delete']) !!}
                                            <button type="submit" class="btn btn-block btn-danger">
                                                Delete
                                            </button>
                                            {!! Form::close() !!}
                                        </td>
                                    </tr>
                                @endforeach
                                    @endif
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@if(false)
    <div class="box box-success box-solid">
        <div class="box-header with-border">
            <h3 class="box-title">Example box</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div>
            <!-- /.box-tools -->
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            Put your content here
        </div>
        <!-- /.box-body -->
    </div>
@endif

resources/views/admin/books/show.blade.php
@extends('adminlte::page')

@section('htmlheader_title')
    Books
@endsection

@section('contentheader_title')
    Books
@endsection

@section('menu_links')
    <li><a href="{!! route('admin.books.index') !!}"><i class="fa fa-book"></i> Books </a></li>
    <li class="active"><i class="fa fa-book"></i> Show book</li>
@endsection

@section('main-content')
    <div class="container-fluid spark-screen">
        <div class="row">
            <div class="col-md-9 col-md-offset-1">
                <div class="panel panel-default">

                    <div class="panel-heading">
                        <h3 class="panel-title">{!! $book->title !!}</h3>
                    </div>

                    <div class="panel-body">
                        <div class="image">
                            <img class="show-image" src="/img/covers/{!! $book->image !!}" alt="">
                        </div>
                        <hr>
                        {!! $book->description !!}
                    </div>

                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-sm-2 col-sm-offset-8">
                                <a class="btn btn-block btn-warning" href="{!! route('admin.authors.edit',['genre' => $book->id]) !!}">
                                    Edit
                                </a>
                            </div>
                            <div class="col-sm-2">
                                {!! Form::open(['route' => ['admin.authors.destroy', 'genre' => $book->id], 'method' => 'delete']) !!}
                                <button type="submit" class="btn btn-block btn-danger">
                                    Delete
                                </button>
                                {!! Form::close() !!}
                            </div>
                        </div>


                    </div>
                </div>

                <h4>Book's comments</h4>

                <div class="list-group">
                    @foreach($book->comments as $comment)
                        <a href="{!! route('admin.comments.edit',['comment' => $comment->id]) !!}" class="list-group-item comment">
                            {{ $comment->text }}
                            <span class="rank"> {!! $comment->rank !!} / 5 </span>
                        </a>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection