routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[
    'uses' => 'HomeController@index',
    'as' => 'home'
]);

Route::group([
    'prefix' => '/admin',
    'middleware' => ['auth','role:owner|admin'],
    'as' => 'admin.'
], function () {

    Route::get('/',[
        'uses' => 'admin\AdminController@index',
        'as' => 'index'
    ]);

    Route::get('/users',[
        'uses' => 'admin\UsersController@index',
        'as' => 'users'
    ]);

    Route::get('/user/{id}',[
        'uses' => 'admin\UsersController@editUser',
        'as' => 'users.edit'
    ]);

    Route::put('/user/{id}/update',[
        'uses' => 'admin\UsersController@updateUser',
        'as' => 'users.update'
    ]);

    Route::post('/user/{id}/roles',[
        'uses' => 'admin\UsersController@updateUserRoles',
        'as' => 'users.roles'
    ]);

    Route::post('/user/{id}/delete',[
        'uses' => 'admin\UsersController@deleteUser',
        'as' => 'users.delete'
    ]);

    Route::get('/roles',[
        'uses' => 'admin\UsersController@permissions',
        'as' => 'permissions',
        'middleware' => 'permission:edit-permissions'
    ]);

    Route::post('/roles/update',[
        'uses' => 'admin\UsersController@updateRole',
        'as' => 'role.update',
        'middleware' => 'permission:edit-permissions'
    ]);

    Route::get('/roles/get',[
        'uses' => 'admin\UsersController@getPermissions',
        'as' => 'role.get',
        'middleware' => 'permission:edit-permissions'
    ]);

    Route::get('/orders',[
        'uses' => 'admin\OrdersController@index',
        'as' => 'orders.get',
    ]);

    //Please do not remove this if you want adminlte:route and adminlte:link commands to works correctly.
    #adminlte_routes
    Route::resource('comments', 'admin\CommentsController');

    Route::resource('authors', 'admin\AuthorsController');

    Route::resource('genres', 'admin\GenresController');

    Route::resource('books', 'admin\BooksController');

});

Route::group([
    'middleware' => 'auth'
], function (){

    Route::post('/book/{id}/comment', [
        'uses' => 'CommentsController@store',
        'as' => 'user.comment.create',
    ]);

    Route::post('/cart', 'CartController@addToCart');

    Route::post('/cart/quantity', 'CartController@getTotalQuantity');

    Route::post('/cart/quantity/add', 'CartController@addItem');

    Route::post('/cart/quantity/deduct', 'CartController@deductItem');

    Route::post('/cart/delete', 'CartController@deleteItem');

    Route::get('/cart/clear', 'CartController@clearCart')->name('user.clear.cart');

    Route::get('/book/{id}', 'BooksController@show')->name('book.show');

    Route::get('/author/{id}', 'AuthorsController@show')->name('author.show');

    Route::get('/genre/{id}', 'GenresController@show')->name('genre.show');


    Route::get('/cart/show', [
        'uses' => 'CartController@show',
        'as' => 'user.cart.show',
    ]);

    Route::post('/cart/show', [
        'uses' => 'CartController@updateStripeDetails',
        'as' => 'user.stripe.update',
    ]);

    Route::post('/cart/buy', [
        'uses' => 'CartController@buy',
        'as' => 'user.buy',
    ]);
});

Route::get('/test', [
    'uses' => 'HomeController@test',
    'as' => 'test'
]);

Route::get('/auth/facebook', [
    'uses' => 'AuthController@fakeLogin',
]);
Route::get('/auth/google', [
    'uses' => 'AuthController@fakeLogin',
]);

Auth::routes();

Route::any('/stripe/webhook', 'WebhookController@handle');

app/models/Comment.php
<?php

namespace App\models;

use App\User;
use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Comment extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [
        'id',
        'text',
        'rank',
        'user_id',
        'book_id'
    ];


    public function book()
    {
        return $this->belongsTo(Book::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

}

app/Http/Controllers/CommentsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;
use App\Http\Requests\CommentCreateRequest;
use App\Repositories\CommentRepository;
use App\Validators\CommentValidator;


class CommentsController extends Controller
{

    /**
     * @var CommentRepository
     */
    protected $repository;

    /**
     * @var CommentValidator
     */
    protected $validator;

    public function __construct(CommentRepository $repository, CommentValidator $validator)
    {
        $this->repository = $repository;
        $this->validator  = $validator;
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  CommentCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(CommentCreateRequest $request, $id)
    {

        try {
            $data = $request->all();
            $data['user_id'] = \Auth::id();
            $data['book_id'] = $id;

            $comment = $this->repository->create($data);

            $response = [
                'message' => 'Comment created.',
                'data'    => $comment->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {
            if ($request->wantsJson()) {
                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

}

app/Http/Controllers/admin/CommentsController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Http\Requests;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;
use App\Http\Requests\CommentCreateRequest;
use App\Http\Requests\CommentUpdateRequest;
use App\Repositories\CommentRepository;
use App\Validators\CommentValidator;


class CommentsController extends Controller
{

    /**
     * @var CommentRepository
     */
    protected $repository;

    /**
     * @var CommentValidator
     */
    protected $validator;

    public function __construct(CommentRepository $repository, CommentValidator $validator)
    {
        $this->repository = $repository;
        $this->validator  = $validator;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->repository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));
        $comments = $this->repository->all();

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $comments,
            ]);
        }

        return view('admin.comments.index', ['comments' => $comments, 'user' => \Auth::user()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  CommentCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(CommentCreateRequest $request)
    {

        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_CREATE);

            $comment = $this->repository->create($request->all());

            $response = [
                'message' => 'Comment created.',
                'data'    => $comment->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->route('admin.comments.index')->with('message', $response['message']);
        } catch (ValidatorException $e) {
            if ($request->wantsJson()) {
                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }


    public function show($id)
    {
        return redirect()->route('admin.comments.index');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $comment = $this->repository->find($id);

        return view('admin.comments.edit', ['comment' => $comment, 'user' => \Auth::user()]);
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  CommentUpdateRequest $request
     * @param  string            $id
     *
     * @return Response
     */
    public function update(CommentUpdateRequest $request, $id)
    {

        try {

            $comment = $this->repository->update($request->all(), $id);

            $response = [
                'message' => 'Comment updated.',
                'data'    => $comment->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->route('admin.comments.index')->with('message', $response['message']);
        } catch (ValidatorException $e) {

            if ($request->wantsJson()) {

                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deleted = $this->repository->delete($id);

        if (request()->wantsJson()) {

            return response()->json([
                'message' => 'Comment deleted.',
                'deleted' => $deleted,
            ]);
        }

        return redirect()->route('admin.comments.index')->with('message', 'Comment deleted.');
    }
}

resources/views/admin/comments/edit.blade.php
@extends('adminlte::page')

@section('htmlheader_title')
    Comments
@endsection

@section('menu_links')
    <li><a href="{!! route('admin.books.index') !!}"><i class="fa fa fa-comments-o"></i> Comments </a></li>
    <li class="active"><i class="fa fa fa-comments-o"></i> Edit Comment</li>
@endsection


@section('main-content')
	<div class="container-fluid spark-screen">
		<div class="row">
			<div class="col-md-9 col-md-offset-1">

				<div class="box box-success box-solid">
                    <div class="box-header with-border">
                        <h3 class="box-title">Example box</h3>
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        </div>
                        <!-- /.box-tools -->
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        Put your content here
                    </div>
                    <!-- /.box-body -->
                </div>

			</div>
		</div>
	</div>
@endsection

resources/views/admin/comments/index.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
    Comments
@endsection

@section('contentheader_title')
    Comments
@endsection

@section('menu_links')
    <li class="active"><i class="fa fa fa-comments-o"></i> Comments</li>
@endsection

@section('main-content')
    <div class="container-fluid spark-screen">
        <div class="row">
            <div class="col-md-9 col-md-offset-1">
                <div class="box box-primary">
                    @if(\Session::has('message'))
                        <div class="alert alert-success" role="alert">
                            {!! Session::get('message') !!}
                        </div>
                    @endif
                    <div class="box-header">
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="table-responsive">
                            <table class="table table-users table-hover">
                                <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Text</th>
                                    <th>Rank</th>
                                    <th>User Name</th>
                                    <th>Book title</th>
                                    <th colspan="2">Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @if( isset($comments))
                                    @foreach($comments as $comment)
                                        <tr>
                                            <td>{!! $comment->id !!}</td>
                                            <td>{!! $comment->text !!}</td>
                                            <td>{!! $comment->rank !!} / 5</td>
                                            <td>{!! $comment->user->name !!}</td>
                                            <td>{!! $comment->book->title !!}</td>
                                            <td>
                                                <a class="btn btn-warning" href="{!! route('admin.comments.edit',['genre' => $comment->id]) !!}">
                                                    Edit
                                                </a>
                                            </td>
                                            <td>
                                                {!! Form::open(['route' => ['admin.comments.destroy', 'genre' => $comment->id], 'method' => 'delete']) !!}
                                                <button type="submit" class="btn btn-danger">
                                                    Delete
                                                </button>
                                                {!! Form::close() !!}
                                            </td>
                                        </tr>
                                    @endforeach
                                @endif
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@if(false)
    <div class="box box-success box-solid">
        <div class="box-header with-border">
            <h3 class="box-title">Example box</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div>
            <!-- /.box-tools -->
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            Put your content here
        </div>
        <!-- /.box-body -->
    </div>
@endif