routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[
    'uses' => 'HomeController@index',
    'as' => 'home'
]);

Route::group([
    'prefix' => '/admin',
    'middleware' => ['auth','role:owner|admin'],
    'as' => 'admin.'
], function () {

    Route::get('/',[
        'uses' => 'admin\AdminController@index',
        'as' => 'index'
    ]);

    Route::get('/users',[
        'uses' => 'admin\UsersController@index',
        'as' => 'users'
    ]);

    Route::get('/user/{id}',[
        'uses' => 'admin\UsersController@editUser',
        'as' => 'users.edit'
    ]);

    Route::put('/user/{id}/update',[
        'uses' => 'admin\UsersController@updateUser',
        'as' => 'users.update'
    ]);

    Route::post('/user/{id}/roles',[
        'uses' => 'admin\UsersController@updateUserRoles',
        'as' => 'users.roles'
    ]);

    Route::post('/user/{id}/delete',[
        'uses' => 'admin\UsersController@deleteUser',
        'as' => 'users.delete'
    ]);

    Route::get('/roles',[
        'uses' => 'admin\UsersController@permissions',
        'as' => 'permissions',
        'middleware' => 'permission:edit-permissions'
    ]);

    Route::post('/roles/update',[
        'uses' => 'admin\UsersController@updateRole',
        'as' => 'role.update',
        'middleware' => 'permission:edit-permissions'
    ]);

    Route::get('/roles/get',[
        'uses' => 'admin\UsersController@getPermissions',
        'as' => 'role.get',
        'middleware' => 'permission:edit-permissions'
    ]);

    Route::get('/orders',[
        'uses' => 'admin\OrdersController@index',
        'as' => 'orders.get',
    ]);

    //Please do not remove this if you want adminlte:route and adminlte:link commands to works correctly.
    #adminlte_routes
    Route::resource('comments', 'admin\CommentsController');

    Route::resource('authors', 'admin\AuthorsController');

    Route::resource('genres', 'admin\GenresController');

    Route::resource('books', 'admin\BooksController');

});

Route::group([
    'middleware' => 'auth'
], function (){

    Route::post('/book/{id}/comment', [
        'uses' => 'CommentsController@store',
        'as' => 'user.comment.create',
    ]);

    Route::post('/cart', 'CartController@addToCart');

    Route::post('/cart/quantity', 'CartController@getTotalQuantity');

    Route::post('/cart/quantity/add', 'CartController@addItem');

    Route::post('/cart/quantity/deduct', 'CartController@deductItem');

    Route::post('/cart/delete', 'CartController@deleteItem');

    Route::get('/cart/clear', 'CartController@clearCart')->name('user.clear.cart');

    Route::get('/book/{id}', 'BooksController@show')->name('book.show');

    Route::get('/author/{id}', 'AuthorsController@show')->name('author.show');

    Route::get('/genre/{id}', 'GenresController@show')->name('genre.show');


    Route::get('/cart/show', [
        'uses' => 'CartController@show',
        'as' => 'user.cart.show',
    ]);

    Route::post('/cart/show', [
        'uses' => 'CartController@updateStripeDetails',
        'as' => 'user.stripe.update',
    ]);

    Route::post('/cart/buy', [
        'uses' => 'CartController@buy',
        'as' => 'user.buy',
    ]);
});

Route::get('/test', [
    'uses' => 'HomeController@test',
    'as' => 'test'
]);

Route::get('/auth/facebook', [
    'uses' => 'AuthController@fakeLogin',
]);
Route::get('/auth/google', [
    'uses' => 'AuthController@fakeLogin',
]);

Auth::routes();

Route::any('/stripe/webhook', 'WebhookController@handle');

app/models/User.php
<?php

namespace App;

use App\models\StripeDetails;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Authenticatable
{
    use Notifiable;
    use EntrustUserTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }

    public function stripeDetails()
    {
        return $this->hasOne(StripeDetails::class);
    }

}

app/Http/Controllers/admin/UsersController.php
<?php

namespace App\Http\Controllers\admin;

use App\models\Permission;
use App\models\Role;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UsersController extends Controller
{
    public function index()
    {
        return view('admin.users.index', ['user' => \Auth::user(),'users' => User::all()]);
    }

    public function editUser($id)
    {
        $redactUser = User::find($id);
        $roles = Role::all();

        return view('admin.users.edit', [
            'user' => \Auth::user(),
            'redactUser' => $redactUser,
            'roles' => $roles
        ]);
    }

    public function updateUser($id, Request $request)
    {
        $redactUser = User::find($id);
        $updateData = $request->except(['_method', '_token']);
        $redactUser->update($updateData);
        $redactUser->save();

        return redirect()->back()->with('message', 'Success!');
    }

    public function updateUserRoles($id ,Request $request)
    {
        $redactUser = User::find($id);
        $roles = $request->get('role');
        foreach ($roles as $roleId){
            $role = Role::find($roleId);
            if ($redactUser->hasRole($role->name)){
                continue;
            } else {
                $redactUser->attachRole($role);
            }
        }
        return redirect()->back()->with('message', 'Success!');
    }

    public function deleteUser($id)
    {
        $redactUser = User::find($id);
        $redactUser->delete();
        return redirect()->back()->with('message', 'Success!');
    }

    public function permissions()
    {
        $roles = Role::with('perms')->get();
        $permissions = Permission::all();

        return view('admin.users.permissions', [
            'user' => \Auth::user(),
            'roles' => $roles,
            'permissions' => $permissions
        ]);
    }

    public function getPermissions(Request $request){
        $role = Role::find($request->get('roleId'));
        return $role->perms->toJson();
    }

    public function updateRole(Request $request){
        $role = Role::find($request->get('role'));
        $role->perms()->detach();
        foreach ($request->get('permissions') as $id) {
            $permission = Permission::find($id);
            $role->perms()->attach($permission);
        }
        return redirect()->back()->with('message', 'Success !');
    }
}

resources/views/admin/users/edit.blade.php
@extends('adminlte::layouts.app')

@section('contentheader_title')
	Users
@endsection

@section('menu_links')
    <li><a href="{!! route('admin.users') !!}"><i class="fa fa-address-card-o"></i> Users </a></li>
    <li class="active"><i class="fa fa-user"></i> Edit User</li>
@endsection


@section('main-content')
	<div class="container-fluid spark-screen">
		<div class="row">
			<div class="col-md-9 col-md-offset-1">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3>Edit User</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="row">
                            <div class="col-sm-6">

                                <div class="panel panel-default">
                                        <div class="panel-body">
                                            {!! \Form::model($redactUser, ['url' => route('admin.users.update', [$id = $redactUser->id]), 'method' => 'put']) !!}
                                            <div class="form-group">
                                                {!! Form::label('name', 'User\'s name' ) !!}
                                                {!! Form::text('name', $redactUser->name,['class' => 'form-control']) !!}
                                            </div>
                                            <div class="form-group">
                                                {!! Form::label('email', 'User\'s email' ) !!}
                                                {!! Form::text('email', $redactUser->email,['class' => 'form-control']) !!}
                                            </div>
                                            <div class="form-group">
                                                {!! Form::label('password', 'User\'s password' ) !!}
                                                {!! Form::password('password',['class' => 'form-control']) !!}
                                            </div>
                                        </div>
                                        <div class="panel-footer">
                                            {!! Form::submit('Update', ['class' => 'btn btn-success']) !!}
                                        </div>
                                    {!! \Form::close() !!}
                                </div>
                            </div>
                            @permission('edit-roles')
                            <div class="col-sm-6">
                                <div class="panel panel-warning">
                                    <div class="panel-heading">
                                        <h3 class="panel-title">User roles</h3>
                                    </div>
                                    {!! Form::open(['url' => route('admin.users.roles', [$id = $redactUser->id]), 'method' => 'post']) !!}
                                    <div class="panel-body">
                                        <div class="form-group">
                                            {!! Form::label('roles', "Roles") !!}
                                        @foreach($roles as $role)
                                                @if($role->name === 'owner')
                                                    @continue
                                                @endif
                                            <div class="checkbox">
                                                <label>
                                                    {!! Form::checkbox('role[]', $role->id , $redactUser->hasRole($role->name) ? true : false) !!}
                                                    {!! $role->display_name !!}
                                                </label>
                                            </div>
                                        @endforeach
                                        </div>
                                    </div>
                                    <div class="panel-footer">
                                        {!! Form::submit('Update roles', ['class' => 'btn btn-warning']) !!}
                                    </div>
                                    {!! Form::close() !!}
                                </div>
                            </div>
                            @endpermission
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('adminlte::layouts.app')

@section('contentheader_title')
	Users
@endsection

@section('menu_links')
    <li class="active"><i class="fa fa-address-card-o"></i> Users</li>
@endsection


@section('main-content')
	<div class="container-fluid spark-screen">
		<div class="row">
			<div class="col-md-9 col-md-offset-1">
                <div class="box box-primary">
                    <div class="box-header">
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="table-responsive">
                            <table class="table table-users table-hover">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th colspan="2">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach($users as $everyUser)
                                    <tr>
                                        <td>{!! $everyUser->id !!}</td>
                                        <td>{!! $everyUser->name !!}</td>
                                        <td>{!! $everyUser->email !!}</td>
                                        <td><a class="btn btn-block btn-success" href="{!! route('admin.users.edit', [$id = $everyUser->id]) !!}">Edit</a></td>
                                        <td><a class="btn btn-block btn-danger" href="{!! route('admin.users.delete', [$id = $everyUser->id]) !!}">Delete</a></td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@if(false)
    <div class="box box-success box-solid">
        <div class="box-header with-border">
            <h3 class="box-title">Example box</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div>
            <!-- /.box-tools -->
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            Put your content here
        </div>
        <!-- /.box-body -->
    </div>
@endif

resources/views/admin/users/permissions.blade.php
@extends('adminlte::page')

@section('contentheader_title')
    Roles & Permissions
@endsection

@section('menu_links')
    <li><a href="{!! route('admin.users') !!}"><i class="fa fa-address-card-o"></i> Users </a></li>
    <li class="active"><i class="fa fa-user"></i> Edit Roles</li>
@endsection


@section('main-content')
    <div class="container-fluid spark-screen">
        <div class="row">
            <div class="col-md-9 col-md-offset-1">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3>Roles & Permissions</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="row">
                            @permission('edit-permissions')
                            <div class="col-sm-6">
                                <div class="panel panel-warning">
                                    <div class="panel-heading">
                                        <h3 class="panel-title">Edit roles</h3>
                                    </div>
                                    {!! Form::open([
                                    'url' => route('admin.role.update'),
                                    'method' => 'post'
                                    ]) !!}
                                    <div class="panel-body">
                                        <div class="form-group">
                                            <label for="role">
                                                Select role to update
                                            </label>
                                            <select name="role" id="role">
                                                <option value="" selected disabled>Select a role</option>
                                                @foreach($roles as $role)
                                                    @if($role->name === 'owner')
                                                        @continue
                                                    @endif
                                                    <option value="{!! $role->id !!}">{!! $role->display_name !!}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            {!! Form::label('permissions', "Permissions") !!}
                                            @foreach($permissions as $permission)
                                                <div class="checkbox">
                                                    <label>
                                                        {!! Form::checkbox('permissions['. $permission->id .']', $permission->id )!!}
                                                        {!! $permission->display_name !!}
                                                    </label>
                                                </div>
                                            @endforeach
                                        </div>
                                    </div>
                                    <div class="panel-footer">
                                        {!! Form::submit('Update roles', ['class' => 'btn btn-warning']) !!}
                                    </div>
                                    {!! Form::close() !!}
                                </div>
                            </div>
                            @endpermission
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    @parent
    <script defer src="../js/roles.js"></script>
@endsection